listener 1883
allow_anonymous false
password_file /run/campus-auth/passwords
acl_file /mosquitto/config/acl
persistence true
persistence_location /mosquitto/data/
autosave_interval 10
log_dest stdout
log_type error
log_type warning
log_type notice
